# Generated by Django 4.1.2 on 2023-04-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='announcements',
            new_name='Announcement',
        ),
    ]
