# Generated by Django 4.1.2 on 2023-05-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_announcement_create_date_announcement_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='user',
            new_name='author',
        ),
    ]
