# Generated by Django 4.1.2 on 2023-05-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_rename_user_announcement_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('1', 'Gry'), ('2', 'Ksiązki'), ('3', 'Filmy'), ('4', 'Elektronika'), ('5', 'Sport'), ('6', 'Muzyka')], default=None, max_length=2),
        ),
    ]
