# Generated by Django 4.1.2 on 2023-05-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_photo_announcement_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='media',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
