# Generated by Django 4.1.2 on 2023-05-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0010_remove_announcement_photos_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
