# Generated by Django 4.1.2 on 2023-05-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0011_announcement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcement/'),
        ),
    ]
