# Generated by Django 4.1.2 on 2023-05-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0013_announcement_available_borrowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
