# Generated by Django 4.1.2 on 2023-05-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0014_alter_announcement_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
