# Generated by Django 4.1.2 on 2023-05-14 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0015_alter_borrowing_borrow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Dostępność'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa produktu'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcement/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('1', 'Gry'), ('2', 'Ksiązki'), ('3', 'Filmy'), ('4', 'Elektronika'), ('5', 'Sport'), ('6', 'Muzyka')], default=None, max_length=2, verbose_name='Rodzaj'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='announcements.announcement', verbose_name='Ogłoszenie'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_date',
            field=models.DateField(verbose_name='Data wypożyczenia'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to=settings.AUTH_USER_MODEL, verbose_name='Wypożyczający'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zwrotu'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='announcements.announcement', verbose_name='Ogłoszenie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(max_length=250, verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Ocena'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
